modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/XII-Mods/issues"

#[[mixins]]
#config="example.common.mixins.json"

[[mods]]
modId="example"
version="${modVersion}"
displayName="Example"
#updateJSONURL="https://api.modrinth.com/updates/example/forge_updates.json"
authors="TonimatasDEV"
description='''
An example mod.
'''

[[dependencies.example]]
modId="neoforge"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.example]]
modId="minecraft"
type="required"
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"